# Site settings
title: FANTASTIC THEM
email: alastor0325@gmail.com
description: The story between Mr.Bear and Mrs.Squarrel.
baseurl: "/fantastic-them" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
instagram_url: https://instagram.com/alastor0325
ee_url: https://instagram.com/escoiattolo

# Build settings
markdown: kramdown
