# Site settings
title: Ti Amo
email: alastor0325@gmail.com
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "/highlights-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
instagram_url: https://instagram.com/alastor0325
ee_url: https://instagram.com/escoiattolo

# Build settings
markdown: kramdown
